when:
  - branch: [main]
    event: push

steps:
  1.18-otp-28-void-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-28-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.18-otp-28-void
        - 1.18.4-otp-28-void

  1.18-otp-28-alpine-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-28-alpine/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.18-otp-28-alpine
        - 1.18.4-otp-28-alpine

  1.18-otp-28-nojit-alpine-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-28-nojit-alpine/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.18-otp-28-nojit-alpine
        - 1.18.4-otp-28-nojit-alpine

  1.18-otp-28-slim-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-28-slim/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - latest
        - 1.18-otp-28-slim
        - 1.18.4-otp-28-slim

  1.18-otp-27-void-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-27-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.18-otp-27-void
        - 1.18.4-otp-27-void

  1.18-otp-27-alpine-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-27-alpine/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.18-otp-27-alpine
        - 1.18.4-otp-27-alpine

  # 1.18-otp-27-nojit-alpine-build-push:
  #   image: reg.hentioe.dev/library/plugin-docker-buildx
  #   privileged: true
  #   pull: true
  #   settings:
  #     repo: hentioe/elixir
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #     dockerfile: 1.18/otp-27-nojit-alpine/Dockerfile
  #     platforms: linux/amd64,linux/arm64/v8
  #     tags:
  #       - 1.18-otp-27-nojit-alpine
  #       - 1.18.4-otp-27-nojit-alpine

  1.18-otp-27-slim-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.18/otp-27-slim/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.18-otp-27-slim
        - 1.18.4-otp-27-slim

  1.17-otp-27-void-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.17/otp-27-void/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.17-otp-27-void
        - 1.17.3-otp-27-void

  1.17-otp-27-alpine-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.17/otp-27-alpine/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.17-otp-27-alpine
        - 1.17.3-otp-27-alpine

  # 1.17-otp-27-nojit-alpine-build-push:
  #   image: reg.hentioe.dev/library/plugin-docker-buildx
  #   privileged: true
  #   pull: true
  #   settings:
  #     repo: hentioe/elixir
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #     dockerfile: 1.17/otp-27-nojit-alpine/Dockerfile
  #     platforms: linux/amd64,linux/arm64/v8
  #     tags:
  #       - 1.17-otp-27-nojit-alpine
  #       - 1.17.3-otp-27-nojit-alpine

  1.17-otp-27-slim-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: hentioe/elixir
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 1.17/otp-27-slim/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 1.17-otp-27-slim
        - 1.17.3-otp-27-slim
